### ISSUE TITLE
Class compile error classname XXX collides with a package when using Eclipse JDT core version > 3.18

### ISSUE THREAD

**Issue by tazmaniax** [tazmaniax/gt-engine#2]
Compiled using version Eclipse JDT Core v3.23

```
chris@tazmaniax % ~/git/play1/play precompile
~        _            _ 
~  _ __ | | __ _ _  _| |
~ | '_ \| |/ _' | || |_|
~ |  __/|_|\____|\__ (_)
~ |_|            |__/   
~
~ play! 1.5.x-1.5.3-22-g8a423b03, https://www.playframework.com
~
~ using java version "14.0.2"
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
Listening for transport dt_socket at address: 8000
Oct 24, 2020 2:43:09 PM play.Logger warn
WARNING: Cannot replace USE_JAVASCRIPT_SOURCE in configuration (useJavaScriptSource=${USE_JAVASCRIPT_SOURCE})
Oct 24, 2020 2:43:09 PM play.Logger warn
WARNING: Cannot replace PROXIMO_URL in configuration (proxy.url=${PROXIMO_URL})
Oct 24, 2020 2:43:09 PM play.Logger warn
WARNING: Cannot replace FRESHDESK_SECRET_KEY in configuration (freshdesk.secretKey=${FRESHDESK_SECRET_KEY})
14:43:09,567 [main] INFO  ~ Starting /Users/chris/git/PlanSocial
:: loading settings :: url = jar:file:/Users/chris/git/play1/framework/lib/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
14:43:09,994 [main] INFO  ~ Module crud is available (/usr/local/play-1.5.x-1.5.3-22-g8a423b03/modules/crud)
14:43:09,994 [main] INFO  ~ Module fastergt is available (/Users/chris/git/PlanSocial/modules/fastergt-1.10)
14:43:09,994 [main] INFO  ~ Module db is available (/Users/chris/git/PlanSocial/modules/db-1.2)
14:43:09,994 [main] INFO  ~ Module accesslog is available (/Users/chris/git/PlanSocial/modules/accesslog-1.2)
14:43:09,995 [main] INFO  ~ Module deadbolt is available (/Users/chris/git/PlanSocial/modules/deadbolt-1.5.4)
14:43:09,995 [main] INFO  ~ Module coffee is available (/Users/chris/git/PlanSocial/modules/coffee-1.0)
14:43:09,995 [main] INFO  ~ Module securesocial is available (/Users/chris/git/PlanSocial/modules/securesocial-0.2.7)
14:43:11,427 [main] INFO  ~ Loaded image cleaner plugin
14:43:11,435 [main] INFO  ~ Precompiling ...
14:43:26,294 [main] ERROR ~ Cannot start in PROD mode with errors
java.lang.RuntimeException: play.template2.exceptions.GTCompilationException: Compile error. classname: play.template2.generated_templates.GTTemplate__app_views_serviceclassgroups_list_html. message: The type GTTemplate__app_views_serviceclassgroups_list_html collides with a package ln: 5
	at play.modules.gtengineplugin.TemplateLoader.getGTTemplateInstance(TemplateLoader.java:95)
	at play.modules.gtengineplugin.TemplateLoader.load(TemplateLoader.java:79)
	at play.modules.gtengineplugin.GTEnginePlugin.loadTemplate(GTEnginePlugin.java:74)
	at play.plugins.PluginCollection.loadTemplate(PluginCollection.java:804)
	at play.templates.TemplateLoader.load(TemplateLoader.java:62)
	at play.templates.TemplateLoader.scan(TemplateLoader.java:278)
	at play.templates.TemplateLoader.scan(TemplateLoader.java:293)
	at play.templates.TemplateLoader.scan(TemplateLoader.java:293)
	at play.templates.TemplateLoader.getAllTemplate(TemplateLoader.java:224)
	at play.Play.preCompile(Play.java:639)
	at play.Play.init(Play.java:324)
	at play.server.Server.main(Server.java:164)
Caused by: play.template2.exceptions.GTCompilationException: play.template2.exceptions.GTCompilationException: Compile error. classname: play.template2.generated_templates.GTTemplate__app_views_serviceclassgroups_list_html. message: The type GTTemplate__app_views_serviceclassgroups_list_html collides with a package ln: 5
	at play.template2.GTTemplateRepo.compileTemplate(GTTemplateRepo.java:316)
	at play.template2.GTTemplateRepo.getTemplateInstance(GTTemplateRepo.java:185)
	at play.template2.GTTemplateRepo.getTemplateInstance(GTTemplateRepo.java:140)
	at play.modules.gtengineplugin.TemplateLoader.getGTTemplateInstance(TemplateLoader.java:87)
	... 11 more
Caused by: play.template2.exceptions.GTCompilationException: Compile error. classname: play.template2.generated_templates.GTTemplate__app_views_serviceclassgroups_list_html. message: The type GTTemplate__app_views_serviceclassgroups_list_html collides with a package ln: 5
	at play.template2.compile.GTJavaCompileToClass$MyICompilerRequestor.acceptResult(GTJavaCompileToClass.java:122)
	at org.eclipse.jdt.internal.compiler.Compiler.processCompiledUnits(Compiler.java:588)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:475)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:426)
	at play.template2.compile.GTJavaCompileToClass.compile(GTJavaCompileToClass.java:271)
	at play.template2.compile.GTCompiler.compile(GTCompiler.java:79)
	at play.template2.GTTemplateRepo.compileTemplate(GTTemplateRepo.java:290)
	... 14 more
```

![CleanShot 2020-10-24 at 14 45 27](https://user-images.githubusercontent.com/1079943/97083413-af814980-1607-11eb-9389-9e4fd504c379.png)

![CleanShot 2020-10-24 at 14 50 17](https://user-images.githubusercontent.com/1079943/97083483-5cf45d00-1608-11eb-839a-b2451da4b769.png)

When compiling with Eclipse JDT Core v3.18 here is the source and compiles output:
Template sources:
![CleanShot 2020-10-24 at 15 05 28](https://user-images.githubusercontent.com/1079943/97083843-e4db6680-160a-11eb-9378-912e91a16bc3.png)

Compiled classes:
![CleanShot 2020-10-24 at 15 07 23](https://user-images.githubusercontent.com/1079943/97083857-f3c21900-160a-11eb-9b8b-7c5d6fb0d6c1.png)

**Comment by tazmaniax** [comment]
It appears there is a naive implementation of `org.eclipse.jdt.internal.compiler.env.INameEnvironment.isPackage(...)` implemented in `play.template2.compile.GTJavaCompileToClass` that incorrectly returns true for "types" in some cases. Here is the output of that method for the different versions of Eclipse JDT Core - they both return consistently incorrect results for types, that being "true". The current implementation returns true if the supplied path is not an existing class, but the name of actual class being compiled is passed in and that is not a class yet so should return false but is returning true.

with Eclipse JDT Core v3.23
```
Package 'GTTemplate_gttemplatelocationwithembeddedsource_generated_key_1' IS A subpackage of 'play.template2.generated_templates'
Package 'java' IS A subpackage of ''
Package 'lang' IS A subpackage of 'java'
Package 'util' IS A subpackage of 'java'
Package 'io' IS A subpackage of 'java'
Package 'play' IS A subpackage of 'play.template2.generated_templates'
Package 'compile' IS A subpackage of 'play.template2'
Package 'Integer' IS A subpackage of 'play.template2.generated_templates'
Package 'Object' IS A subpackage of 'play.template2.generated_templates'
Package 'PrintWriter' IS A subpackage of 'play.template2.generated_templates'
```
with Eclipse JDT Core v3.18
```
Package 'GTTemplate_gttemplatelocationwithembeddedsource_generated_key_1' IS A subpackage of 'play.template2.generated_templates'
Package 'java' IS A subpackage of ''
Package 'lang' IS A subpackage of 'java'
Package 'util' IS A subpackage of 'java'
Package 'io' IS A subpackage of 'java'
Package 'play' IS A subpackage of 'play.template2.generated_templates'
Package 'compile' IS A subpackage of 'play.template2'
Package 'Integer' IS A subpackage of 'play.template2.generated_templates'
Package 'Object' IS A subpackage of 'play.template2.generated_templates'
Package 'PrintWriter' IS A subpackage of 'play.template2.generated_templates'
Package 'GTTemplate_gttemplatelocationwithembeddedsource_generated_key_2' IS A subpackage of 'play.template2.generated_templates'
Package 'java' IS A subpackage of ''
Package 'lang' IS A subpackage of 'java'
Package 'util' IS A subpackage of 'java'
Package 'io' IS A subpackage of 'java'
Package 'play' IS A subpackage of 'play.template2.generated_templates'
Package 'compile' IS A subpackage of 'play.template2'
Package 'Integer' IS A subpackage of 'play.template2.generated_templates'
Package 'Object' IS A subpackage of 'play.template2.generated_templates'
Package 'PrintWriter' IS A subpackage of 'play.template2.generated_templates'
Package 'GTTemplate_gttemplatelocationwithembeddedsource_generated_key_3' IS A subpackage of 'play.template2.generated_templates'
Package 'java' IS A subpackage of ''
Package 'lang' IS A subpackage of 'java'
Package 'util' IS A subpackage of 'java'
Package 'io' IS A subpackage of 'java'
Package 'play' IS A subpackage of 'play.template2.generated_templates'
Package 'compile' IS A subpackage of 'play.template2'
Package 'Integer' IS A subpackage of 'play.template2.generated_templates'
Package 'Object' IS A subpackage of 'play.template2.generated_templates'
Package 'PrintWriter' IS A subpackage of 'play.template2.generated_templates'
Package 'GTTemplate_gttemplatelocationwithembeddedsource_generated_key_4' IS A subpackage of 'play.template2.generated_templates'
Package 'java' IS A subpackage of ''
Package 'lang' IS A subpackage of 'java'
Package 'util' IS A subpackage of 'java'
Package 'io' IS A subpackage of 'java'
Package 'play' IS A subpackage of 'play.template2.generated_templates'
Package 'compile' IS A subpackage of 'play.template2'
Package 'Integer' IS A subpackage of 'play.template2.generated_templates'
Package 'Object' IS A subpackage of 'play.template2.generated_templates'
Package 'PrintWriter' IS A subpackage of 'play.template2.generated_templates'
Package 'GTTemplate_gttemplatelocationwithembeddedsource_generated_key_5' IS A subpackage of 'play.template2.generated_templates'
Package 'java' IS A subpackage of ''
Package 'lang' IS A subpackage of 'java'
Package 'util' IS A subpackage of 'java'
Package 'io' IS A subpackage of 'java'
Package 'play' IS A subpackage of 'play.template2.generated_templates'
Package 'compile' IS A subpackage of 'play.template2'
Package 'Integer' IS A subpackage of 'play.template2.generated_templates'
Package 'Object' IS A subpackage of 'play.template2.generated_templates'
Package 'PrintWriter' IS A subpackage of 'play.template2.generated_templates'
Package 'GTTemplate_gttemplatelocationwithembeddedsource_generated_key_6' IS A subpackage of 'play.template2.generated_templates'
Package 'java' IS A subpackage of ''
Package 'lang' IS A subpackage of 'java'
Package 'util' IS A subpackage of 'java'
Package 'io' IS A subpackage of 'java'
Package 'play' IS A subpackage of 'play.template2.generated_templates'
Package 'compile' IS A subpackage of 'play.template2'
Package 'Integer' IS A subpackage of 'play.template2.generated_templates'
Package 'Object' IS A subpackage of 'play.template2.generated_templates'
Package 'PrintWriter' IS A subpackage of 'play.template2.generated_templates'
Package 'GTTemplate_gttemplatelocationwithembeddedsource_generated_key_7' IS A subpackage of 'play.template2.generated_templates'
Package 'java' IS A subpackage of ''
Package 'lang' IS A subpackage of 'java'
Package 'util' IS A subpackage of 'java'
Package 'io' IS A subpackage of 'java'
Package 'play' IS A subpackage of 'play.template2.generated_templates'
Package 'compile' IS A subpackage of 'play.template2'
Package 'Integer' IS A subpackage of 'play.template2.generated_templates'
Package 'Object' IS A subpackage of 'play.template2.generated_templates'
Package 'PrintWriter' IS A subpackage of 'play.template2.generated_templates'
```

**Comment by tazmaniax** [comment]
I added a small hack to return false if the child package started with a capital letter, which should not be the case for most actual packages, and this means it completes successfully.

with Eclipse JDT Core v3.23
```
Package 'GTTemplate_gttemplatelocationwithembeddedsource_generated_key_1' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'java' IS A subpackage of ''
Package 'lang' IS A subpackage of 'java'
Package 'util' IS A subpackage of 'java'
Package 'io' IS A subpackage of 'java'
Package 'play' IS A subpackage of 'play.template2.generated_templates'
Package 'compile' IS A subpackage of 'play.template2'
Package 'Integer' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'Object' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'PrintWriter' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'GTTemplate_gttemplatelocationwithembeddedsource_generated_key_2' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'java' IS A subpackage of ''
Package 'lang' IS A subpackage of 'java'
Package 'util' IS A subpackage of 'java'
Package 'io' IS A subpackage of 'java'
Package 'play' IS A subpackage of 'play.template2.generated_templates'
Package 'compile' IS A subpackage of 'play.template2'
Package 'Integer' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'Object' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'PrintWriter' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'GTTemplate_gttemplatelocationwithembeddedsource_generated_key_3' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'java' IS A subpackage of ''
Package 'lang' IS A subpackage of 'java'
Package 'util' IS A subpackage of 'java'
Package 'io' IS A subpackage of 'java'
Package 'play' IS A subpackage of 'play.template2.generated_templates'
Package 'compile' IS A subpackage of 'play.template2'
Package 'Integer' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'Object' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'PrintWriter' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'GTTemplate_gttemplatelocationwithembeddedsource_generated_key_4' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'java' IS A subpackage of ''
Package 'lang' IS A subpackage of 'java'
Package 'util' IS A subpackage of 'java'
Package 'io' IS A subpackage of 'java'
Package 'play' IS A subpackage of 'play.template2.generated_templates'
Package 'compile' IS A subpackage of 'play.template2'
Package 'Integer' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'Object' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'PrintWriter' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'GTTemplate_gttemplatelocationwithembeddedsource_generated_key_5' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'java' IS A subpackage of ''
Package 'lang' IS A subpackage of 'java'
Package 'util' IS A subpackage of 'java'
Package 'io' IS A subpackage of 'java'
Package 'play' IS A subpackage of 'play.template2.generated_templates'
Package 'compile' IS A subpackage of 'play.template2'
Package 'Integer' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'Object' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'PrintWriter' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'GTTemplate_gttemplatelocationwithembeddedsource_generated_key_6' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'java' IS A subpackage of ''
Package 'lang' IS A subpackage of 'java'
Package 'util' IS A subpackage of 'java'
Package 'io' IS A subpackage of 'java'
Package 'play' IS A subpackage of 'play.template2.generated_templates'
Package 'compile' IS A subpackage of 'play.template2'
Package 'Integer' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'Object' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'PrintWriter' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'GTTemplate_gttemplatelocationwithembeddedsource_generated_key_7' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'java' IS A subpackage of ''
Package 'lang' IS A subpackage of 'java'
Package 'util' IS A subpackage of 'java'
Package 'io' IS A subpackage of 'java'
Package 'play' IS A subpackage of 'play.template2.generated_templates'
Package 'compile' IS A subpackage of 'play.template2'
Package 'Integer' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'Object' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'PrintWriter' IS NOT A subpackage of 'play.template2.generated_templates'
```

with Eclipse JDT Core v3.18
```
Package 'GTTemplate_gttemplatelocationwithembeddedsource_generated_key_1' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'java' IS A subpackage of ''
Package 'lang' IS A subpackage of 'java'
Package 'util' IS A subpackage of 'java'
Package 'io' IS A subpackage of 'java'
Package 'play' IS A subpackage of 'play.template2.generated_templates'
Package 'compile' IS A subpackage of 'play.template2'
Package 'Integer' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'Object' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'PrintWriter' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'GTTemplate_gttemplatelocationwithembeddedsource_generated_key_2' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'java' IS A subpackage of ''
Package 'lang' IS A subpackage of 'java'
Package 'util' IS A subpackage of 'java'
Package 'io' IS A subpackage of 'java'
Package 'play' IS A subpackage of 'play.template2.generated_templates'
Package 'compile' IS A subpackage of 'play.template2'
Package 'Integer' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'Object' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'PrintWriter' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'GTTemplate_gttemplatelocationwithembeddedsource_generated_key_3' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'java' IS A subpackage of ''
Package 'lang' IS A subpackage of 'java'
Package 'util' IS A subpackage of 'java'
Package 'io' IS A subpackage of 'java'
Package 'play' IS A subpackage of 'play.template2.generated_templates'
Package 'compile' IS A subpackage of 'play.template2'
Package 'Integer' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'Object' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'PrintWriter' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'GTTemplate_gttemplatelocationwithembeddedsource_generated_key_4' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'java' IS A subpackage of ''
Package 'lang' IS A subpackage of 'java'
Package 'util' IS A subpackage of 'java'
Package 'io' IS A subpackage of 'java'
Package 'play' IS A subpackage of 'play.template2.generated_templates'
Package 'compile' IS A subpackage of 'play.template2'
Package 'Integer' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'Object' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'PrintWriter' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'GTTemplate_gttemplatelocationwithembeddedsource_generated_key_5' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'java' IS A subpackage of ''
Package 'lang' IS A subpackage of 'java'
Package 'util' IS A subpackage of 'java'
Package 'io' IS A subpackage of 'java'
Package 'play' IS A subpackage of 'play.template2.generated_templates'
Package 'compile' IS A subpackage of 'play.template2'
Package 'Integer' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'Object' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'PrintWriter' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'GTTemplate_gttemplatelocationwithembeddedsource_generated_key_6' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'java' IS A subpackage of ''
Package 'lang' IS A subpackage of 'java'
Package 'util' IS A subpackage of 'java'
Package 'io' IS A subpackage of 'java'
Package 'play' IS A subpackage of 'play.template2.generated_templates'
Package 'compile' IS A subpackage of 'play.template2'
Package 'Integer' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'Object' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'PrintWriter' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'GTTemplate_gttemplatelocationwithembeddedsource_generated_key_7' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'java' IS A subpackage of ''
Package 'lang' IS A subpackage of 'java'
Package 'util' IS A subpackage of 'java'
Package 'io' IS A subpackage of 'java'
Package 'play' IS A subpackage of 'play.template2.generated_templates'
Package 'compile' IS A subpackage of 'play.template2'
Package 'Integer' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'Object' IS NOT A subpackage of 'play.template2.generated_templates'
Package 'PrintWriter' IS NOT A subpackage of 'play.template2.generated_templates'
```
